### ISSUE TITLE
How to install Berkeley DB

### ISSUE THREAD

**Issue by rchastain** [thgreiner/amy#2]
Please could you explain how to install Berkeley DB? Is an Oracle account needed?

I am on Linux Mageia.

Viele Grüße.

Roland

**Comment by thgreiner** [comment]
Hi Roland,

while I can‘t help you with that specific Linux version, you should be able to download and compile BerkeleyDB directly from source without an Oracle account. Here is a step-by-step guide I found: https://noknow.info/it/os/install_oracle_berkeley_db_from_source

Hope that helps!

Best,

-Thorsten

**Comment by thgreiner** [comment]
Hi Roland,

while I can‘t help you with that specific Linux version, you should be able to download and compile BerkeleyDB directly from source without an Oracle account. Here is a step-by-step guide I found: https://noknow.info/it/os/install_oracle_berkeley_db_from_source

Hope that helps!

Best,

-Thorsten
